### ISSUE TITLE
Cannot find module 'node-uuid'

### ISSUE THREAD

**Issue by Math3v** [trailsjs/trailpack-knex#119]
- `npm install trailpack-knex sqlite3 --save`
- `main.js`
```
// ...
  packs: [
    require('trailpack-repl'),
    require('trailpack-router'),
    require('trailpack-hapi'),
    require('trailpack-waterline'),
    require('trailpack-footprints'),
    require('trailpack-knex')
  ]
```
- `npm start`

Error:
```
module.js:471
    throw err;
    ^

Error: Cannot find module 'node-uuid'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/matej/dev/trails-sample/node_modules/knex/lib/raw.js:24:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/matej/dev/trails-sample/node_modules/knex/lib/index.js:8:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```

**Comment by johnazre** [comment]
I'm having this issue right now, too. If the project is built with Waterline, NPM doesn't fail, but with this trailpack-knex, it fails with this as an output:
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for trailpack-knex@v2-latest
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/blah/.npm/_logs/2017-10-29T22_45_57_171Z-debug.log
```

Then, if I `npm install --save trailpack-knex`, your error appears.
